# Generated by Django 5.0.14 on 2026-09-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tourist', 'Tourist'), ('guide', 'Guide'), ('admin', 'Administrator')], default='tourist', max_length=20),
        ),
    ]
