# Generated by Django 5.2.3 on 2026-09-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tourist', 'Tourist'), ('guide', 'Guide'), ('admin', 'Administrator'), ('referral_agent', 'Referral Agent')], default='tourist', max_length=20),
        ),
    ]
