# Generated by Django 5.0.14 on 2026-09-11 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('guides', '0002_guide_user'),
        ('region_safaris', '0001_initial'),
        ('safaris', '0004_remove_safaripackage_region_safaripackage_parks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='region_safari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='region_safaris.regionsafari'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='safari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='safaris.safaripackage'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('region_safari__isnull', True), ('safari__isnull', False)), models.Q(('region_safari__isnull', False), ('safari__isnull', True)), _connector='OR'), name='booking_has_exactly_one_product'),
        ),
    ]
