# Generated by Django 5.0.14 on 2026-09-12 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_region_safari_alter_booking_safari_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('day', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('current', 'Current'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('photo', models.URLField(blank=True, max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='bookings.booking')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
