# Generated by Django 5.0.14 on 2026-09-12 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_tripmilestone'),
        ('guides', '0003_guide_bio_guide_languages_guide_specialties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_rating', models.PositiveSmallIntegerField()),
                ('trip_rating', models.PositiveSmallIntegerField()),
                ('testimonial', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='guides.guide')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
