# Generated by Django 5.0.14 on 2026-09-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelineitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
