# Generated by Django 5.2.3 on 2026-09-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_quotelineitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='trip_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
