# Generated by Django 5.0.14 on 2026-09-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('Senior Guide', 'Senior Guide'), ('Expert Guide', 'Expert Guide'), ('Driver-Guide', 'Driver-Guide'), ('Camp Chef', 'Camp Chef'), ('Tour Helper', 'Tour Helper')], max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('Off-Duty', 'Off-Duty')], default='Available', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
            ],
        ),
    ]
