# Generated by Django 5.0.14 on 2026-09-12 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_guide_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='guide',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='GuideCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('document', models.URLField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='guides.guide')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
