# Generated by Django 5.2.3 on 2026-09-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('visited', 'Visited Trip Curator'), ('started', 'Started Choosing Experiences'), ('submitted', 'Submitted Inquiry')], max_length=20)),
                ('session_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['step'], name='analytics_f_step_81c9ee_idx')],
            },
        ),
    ]
