# Generated by Django 5.0.14 on 2026-09-05 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafariPackage',
            fields=[
                ('slug', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('image', models.URLField(max_length=500)),
                ('image_alt', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('days', models.PositiveIntegerField()),
                ('accommodation', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField()),
                ('badge', models.CharField(blank=True, max_length=64)),
                ('signature', models.BooleanField(default=False)),
                ('destination', models.CharField(choices=[('Serengeti National Park', 'Serengeti National Park'), ('Ngorongoro Conservation Area', 'Ngorongoro Conservation Area'), ('Tarangire & Manyara', 'Tarangire & Manyara'), ('Zanzibar Extensions', 'Zanzibar Extensions')], max_length=40)),
                ('overview', models.TextField()),
                ('highlights', models.JSONField(default=list)),
                ('included', models.JSONField(default=list)),
                ('excluded', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('safari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='safaris.safaripackage')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
