# Generated by Django 5.0.14 on 2026-09-07 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('safaris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackage',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safaris', to='destinations.destination'),
        ),
    ]
