# Generated by Django 5.0.14 on 2026-09-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaris', '0002_safaripackage_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackage',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
