# Generated by Django 5.0.14 on 2026-09-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_park'),
        ('safaris', '0003_safaripackage_gallery_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safaripackage',
            name='region',
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='parks',
            field=models.ManyToManyField(blank=True, related_name='safaris', to='destinations.park'),
        ),
    ]
