# Generated by Django 5.0.14 on 2026-09-05 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('slug', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('images', models.JSONField(default=list)),
                ('image_alt', models.CharField(max_length=255)),
                ('badge', models.CharField(max_length=64)),
                ('tags', models.JSONField(default=list)),
                ('best_time_to_visit', models.CharField(max_length=120)),
                ('highlight', models.CharField(max_length=255)),
                ('link_label', models.CharField(max_length=64)),
                ('about', models.TextField()),
                ('wildlife', models.TextField()),
                ('getting_there', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DestinationExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='destinations.destination')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
