# Generated by Django 5.0.14 on 2026-09-07 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('slug', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('images', models.JSONField(blank=True, default=list)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('badge', models.CharField(blank=True, max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=120)),
                ('highlight', models.CharField(blank=True, max_length=255)),
                ('about', models.TextField(blank=True)),
                ('wildlife', models.TextField(blank=True)),
                ('getting_there', models.TextField(blank=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parks', to='destinations.destination')),
            ],
        ),
    ]
